<?php
/**
 * The intit file for incudin all file all functions
 * 
 * @package best-it
 */

// include theme support file.....
require get_template_directory() . '/lib/theme-support.php';

// include breadcrumbs section  file.....
require get_template_directory() . '/template-part/breadcrumbs.php';

// include menu function file.....
require get_template_directory() . '/lib/menu.php';

// include header top customizer function file.....
require get_template_directory() . '/lib/customizer/header-top-customizer.php';
// include header top  file.....
require get_template_directory() . '/template-part/header/header-top.php';

// include slider  file.....
require get_template_directory() . '/lib/slider.php';
// include slider display section  file.....
require get_template_directory() . '/template-part/home/slider.php';
// include slider customizer function file.....
require get_template_directory() . '/lib/customizer/slider-customizer.php';

// include about section  file.....
require get_template_directory() . '/template-part/home/about.php';
// include about us customizer function file.....
require get_template_directory() . '/lib/customizer/about-customizer.php';

// include services function file.....
require get_template_directory() . '/lib/services.php';

// include about section  file.....
require get_template_directory() . '/template-part/home/service.php';

// include service customizer function file.....
require get_template_directory() . '/lib/customizer/service-customizer.php';


// include speatial section customizer function file.....
require get_template_directory() . '/lib/customizer/speatial_section_customizer.php';
// include speatial section  file.....
require get_template_directory() . '/template-part/home/Speatial_section.php';

// include feature section  file.....
require get_template_directory() . '/template-part/home/feature.php';
// include feature customizer function file.....
require get_template_directory() . '/lib/customizer/feature-customizer.php';


// include testimonial function file.....
require get_template_directory() . '/lib/testimonial.php';

// include portfolio function file.....
require get_template_directory() . '/lib/portfolio.php';

// include testimonial customizer function file.....
require get_template_directory() . '/lib/customizer/testimonial-customizer.php';
// include testimonial section  file.....
require get_template_directory() . '/template-part/footer/testimonial.php';


// include parallax customizer function file.....
require get_template_directory() . '/lib/customizer/parallax-customizer.php';

// include parllax section  file.....
require get_template_directory() . '/template-part/home/parallax.php';


// include footer widgets
require get_template_directory() . '/lib/widgets/footer-widgets.php';
// include footer widgets section  file.....
require get_template_directory() . '/template-part/footer/footer-widgets.php';

// include copy right customizer function file.....
require get_template_directory() . '/lib/customizer/copy-right-customizer.php';
// include copy right section  file.....
require get_template_directory() . '/template-part/footer/copyright.php';